### ISSUE TITLE
Scroll Lock Light/Key seems to not be working.

### ISSUE THREAD

**Issue by newm-newm** [xelalexv/suniversal#2]
Type 5c; On Ubuntu Linux.

Num Lock and Caps lock seem to be working but the scroll lock key doesn't seem to be working.

**Comment by xelalexv** [comment]
This is most likely because the handling of Scroll Lock is turned off in your system. Was the same on mine, also with other keyboards. Using `xev`, I could see that the scroll lock key code is correctly sent, but the LED is not toggled.

Could you try this: `xmodmap -pm`, pick an unassigned modifier, usually that would be `mod3`, and then do `xmodmap -e "add mod3 = Scroll_Lock"`. After that the scroll lock LED should work. The first reply to [this question](https://unix.stackexchange.com/questions/164245/why-is-the-scroll-lock-key-disabled-in-cinnamon-linux-xorg) has more details, also on how you make this persistent.

**Comment by xelalexv** [comment]
Does this solve the issue? If so, I'd like to close it.
